# Generated by Django 5.0.7 on 2024-11-15 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_account_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='tranction_type',
            new_name='transaction_type',
        ),
    ]
